[workspace]
members = ["packages/chrono"]

[workspace.package]
version = "0.1.0"
edition = "2024_07"
cairo-version = "2.11.2"
scarb-version = "2.11.3"
authors = ["KaizeNodeLabs Community"]
description = "Community maintained Cairo and Starknet libraries"
documentation = "https://github.com/KaizeNodeLabs/starkiro"
homepage = "https://github.com/KaizeNodeLabs/starkiro"
repository = "https://github.com/KaizeNodeLabs/starkiro"
license-file = "LICENSE"

[workspace.dependencies]
starknet = "2.11.2"
assert_macros = "2.11.2"
snforge_std = "0.39.0"

[workspace.tool.fmt]
sort-module-level-items = true

[workspace.tool.scarb]
allow-prebuilt-plugins = ["snforge_std"]

[workspace.scripts]
test = "snforge test --max-n-steps 1000000000"
