[package]
name = "examples"
version = "0.1.0"
edition = "2024_07"
publish = false

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
string_utility = "0.1.0"

[dev-dependencies]
cairo_test = "2.9.2"
