[package]
name = "string_utility"
version = "0.1.0"
description = "Library providing essential operations for string manipulation"
repository = "https://github.com/KaizeNodeLabs/starkiro/tree/main/examples/cairo/scripts/string_utility"
edition = "2024_07"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[lib]
crate-type = ["lib"]

[dependencies]

[dev-dependencies]
cairo_test = "2.9.2"
