name: snforge Contract Test

on:
  push:
    branches: ["main"]
    paths:
      - "src/**"
      - "tests/**"
  pull_request:
    branches: ["main"]
    paths:
      - "src/**"
      - "tests/**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Scarb
        uses: software-mansion/setup-scarb@v1
        with:
          scarb-version: "2.3.1"

      - name: Install snforge
        run: curl -L https://raw.githubusercontent.com/foundry-rs/starknet-foundry/master/scripts/install.sh | sh

      - name: Run snforge tests
        run: snforge test

      - name: Upload test logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-logs
          path: target/snforge/*.log
