name: Test Starkiro Contracts

on:
  push:
    branches: ["fix/snforge-workflow"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: ['hello_world', 'counter']  # Add your contract project names here
    
    steps:
      - uses: actions/checkout@v4

      - name: Setup Scarb
        uses: software-mansion/setup-scarb@v1
        with:
          scarb-version: "2.3.1"

      - name: Setup Starknet Foundry
        uses: foundry-rs/setup-snfoundry@v3

      - name: Build and Test ${{ matrix.project }}
        working-directory: ./starknet/contracts/${{ matrix.project }}
        run: |
          scarb build
          snforge test

      - name: Upload test logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-logs-${{ matrix.project }}
          path: ./starknet/contracts/${{ matrix.project }}/target/
          retention-days: 3
