name: Test Starkiro Contracts

on:
  push:
    branches: ["fix/snforge-workflow"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: ['counter_access_control', 'crowdfunding', 'escrow_multiple_recipients', 'flip_flop', 'hello_world', 'random_number_generator', 'sbt', 'simple_counter', 'simple_erc20', 'simple_erc721', 'staking', 'token_vesting']
      max-parallel: 4

    steps:
      - uses: actions/checkout@v4

      - name: Setup Scarb
        uses: software-mansion/setup-scarb@v1
        with:
          scarb-version: "2.9.2"

      - name: Setup Starknet Foundry
        uses: foundry-rs/setup-snfoundry@v3

      - name: Verify contract directory exists
        run: |
          if [ ! -d "./starknet/contracts/${{ matrix.project }}" ]; then
            echo "Directory ./starknet/contracts/${{ matrix.project }} not found!"
            exit 1
          fi

      - name: Build and Test ${{ matrix.project }}
        working-directory: ./starknet/contracts/${{ matrix.project }}
        run: |
          scarb build || { echo "Scarb build failed"; exit 1; }
          snforge test || { echo "Tests failed"; exit 1; }

      - name: Upload test logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-logs-${{ matrix.project }}
          path: ./starknet/contracts/${{ matrix.project }}/target/
          retention-days: 3
