name: Test Starkiro Contracts

on:
  push:
    branches: ["main"]
    paths:
      - "src/**"
      - "tests/**"
      - "Scarb.toml"
  pull_request:
    branches: ["main"]
    paths:
      - "src/**"
      - "tests/**"
      - "Scarb.toml"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Scarb
        uses: software-mansion/setup-scarb@v1
        with:
          scarb-version: "2.3.1"

      - name: Setup Starknet Foundry
        uses: foundry-rs/setup-snfoundry@v3
        with:
          starknet-foundry-version: "0.12.0"

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.scarb
            target/
          key: ${{ runner.os }}-scarb-${{ hashFiles('**/Scarb.toml') }}
          restore-keys: |
            ${{ runner.os }}-scarb-

      - name: Build contracts
        run: scarb build

      - name: Run tests
        run: snforge test

      - name: Upload test logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-logs
          path: |
            target/snforge/*.log
            target/dev/*.sierra
          retention-days: 7
